CO5227_Assignment/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CO5227_Assignment.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CO5227_Assignment/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Identity.Client;
using Microsoft.AspNetCore.Identity;
using CO5227_Assignment.Data;
using CO5227_Assignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http.Features;

namespace CO5227_Assignment.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly CO5227_AssignmentContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        public OrderHistory Order = new OrderHistory();
        public IList<CheckoutItem> Items { get; private set; }

        public decimal Total;
        public long AmountPayable;

        public CheckoutModel(CO5227_AssignmentContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                CheckoutCustomer customer = await _db.CheckoutCustomers.FindAsync(user.Email);

                Items = _db.CheckoutItems.FromSqlRaw(
                    "SELECT MenuItems.itemID, MenuItems.price, MenuItems.itemName, BasketItems.BasketID, BasketItems.Quantity " +
                    "FROM MenuItems INNER JOIN BasketItems ON MenuItems.itemID = BasketItems.StockID WHERE BasketID = {0}",
                    customer.BasketID).ToList();

                Total = 0;

                

                foreach (var item in Items)
                {
                    Total += (item.quantity * (decimal)item.price);
                }
                AmountPayable = (long)Total;
            }
             
        }

        public async Task<IActionResult> OnPostBuyAsync()
        {
            var currentOrder = _db.OrderHistories.FromSqlRaw("SELECT * FROM OrderHistories").OrderByDescending(b=> b.OrderNo).FirstOrDefault();

            if(currentOrder == null)
            {
                Order.OrderNo = 1;
            }
            else
            {
                Order.OrderNo = currentOrder.OrderNo+ 1;
            }

            var user = await _userManager.GetUserAsync(User);
            Order.Email = user.Email;
            _db.OrderHistories.Add(Order);

            CheckoutCustomer customer = await _db.CheckoutCustomers.FindAsync(user.Email);

            var basketItems = _db.BasketItems.FromSqlRaw("SELECT * FROM BasketItems WHERE BasketID = {0}", customer.BasketID).ToList();

            foreach(var item in basketItems)
            {
                OrderItem oi = new OrderItem
                {
                    OrderNo = Order.OrderNo,
                    StockID = item.StockID,
                    Quantity = item.Quantity
                };

                _db.OrderItems.Add(oi);
                _db.BasketItems.Remove(item);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction("/Index");
        }
    }
}

CO5227_Assignment/Pages/Contact.cshtml.cs
using CO5227_Assignment.Areas.Email.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CO5227_Assignment.Pages
{
    public class ContactModel : PageModel
    {
        private readonly IEmailSender _emailSender;
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Subject { get; set; }
        [BindProperty]
        public string Body { get; set; }

        
        public bool? isSuccessful = null;
        
        
        public ContactModel(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        
        public async Task<IActionResult> OnPostSubmitAsync()
        {
            //Attempt to send email and set isSuccessful to track whether it was successfull or not
            try
            {
                await _emailSender.SendEmailAsync(Email, Subject, Body);
                isSuccessful = true;
                return Page();
            }catch (Exception ex)
            {
                isSuccessful = false;
                return Page();
            }
            
        }
        public void OnGet()
        {
        }
    }
}

CO5227_Assignment/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CO5227_Assignment.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CO5227_Assignment/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using CO5227_Assignment.Data;
using CO5227_Assignment.wwwroot.Models;
using Microsoft.EntityFrameworkCore;

namespace CO5227_Assignment.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly CO5227_AssignmentContext _context;

        public IndexModel(ILogger<IndexModel> logger, CO5227_AssignmentContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IList<MenuItems> signatures { get; set; } = default!;
        public IList<MenuItems> allMenuItems { get; set; } = default!;
        public void OnGet()
        {
            //retrieves all special items from menuItems and saves it to signatures
            signatures = _context.MenuItemss.FromSqlRaw("Select * From MenuItems WHERE special = 1").ToList();
            //retrieves all menuItems and saves it to allMenuItems
            allMenuItems = _context.MenuItemss.FromSqlRaw("Select * From MenuItems").ToList();
        }
    }
}

CO5227_Assignment/Pages/adminPortal.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace CO5227_Assignment.Pages
{
    [Authorize (Roles = "Admin")]
    public class adminPortalModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CO5227_Assignment/Pages/userMenu.cshtml.cs
using CO5227_Assignment.wwwroot.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using CO5227_Assignment.Data;
using CO5227_Assignment.Models;

namespace CO5227_Assignment.Pages.AdminMenu
{
    public class userMenuModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly CO5227_AssignmentContext _db;
        public userMenuModel(CO5227_AssignmentContext db,UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnPostBuyAsync(string itemID)
        {
            var user = await _userManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db.CheckoutCustomers.FindAsync(user.Email);

            var item = _db.BasketItems.FromSqlRaw("SELECT * FROM BasketItems WHERE StockID = {0}" +
                " AND BasketID = {1}", itemID, customer.BasketID).ToList().FirstOrDefault();

            if (item == null) {
                BasketItem newItem = new BasketItem
                {
                    BasketID = customer.BasketID,
                    StockID = itemID,
                    Quantity = 1
                };
                _db.BasketItems.Add(newItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                item.Quantity = item.Quantity + 1;
                _db.Attach(item).State = EntityState.Modified;
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex) {
                    throw new Exception($"Basket not found!", ex);
                }
            }
            return RedirectToPage();

        }

        //private readonly CO5227_Assignment.Data.CO5227_AssignmentContext _context;

        //public userMenuModel(CO5227_Assignment.Data.CO5227_AssignmentContext context)
        //{
        //    _context = context;
        //}

        public IList<MenuItems> MenuItems { get; set; } = default!;

        public async Task OnGetAsync()
        {
            if (_db.MenuItemss != null)
            {
                MenuItems = await _db.MenuItemss.ToListAsync();
            }
        }
    }
}

CO5227_Assignment/Pages/userMenuIndex.cshtml.cs
using CO5227_Assignment.wwwroot.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using CO5227_Assignment.Data;
using CO5227_Assignment.Models;

namespace CO5227_Assignment.Pages.AdminMenu
{
    public class userMenuModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly CO5227_AssignmentContext _db;

        [BindProperty]
        public string Search {  get; set; }

        public IList<MenuItems> MenuItems { get; set; } = default!;

        public userMenuModel(CO5227_AssignmentContext db,UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult OnPostSearch()
        {
            //Sets state of MenuItems list to menuItems that are similar to what the user inputted as Search
            MenuItems = _db.MenuItemss.FromSqlRaw("SELECT * FROM MenuItems Where itemName LIKE '" + Search +"%'").ToList();
            return Page();
        }

        public async Task<IActionResult> OnPostBuyAsync(string itemID)
        {
            //get user and associated checkoutcustomer
            var user = await _userManager.GetUserAsync(User);
            CheckoutCustomer customer = await _db.CheckoutCustomers.FindAsync(user.Email);

            //retrieve instances of itemm from basket
            var item = _db.BasketItems.FromSqlRaw("SELECT * FROM BasketItems WHERE StockID = {0}" +
                " AND BasketID = {1}", itemID, customer.BasketID).ToList().FirstOrDefault();

            //if item doesnt exist, add it, otherwise increase quantity
            if (item == null) {
                BasketItem newItem = new BasketItem
                {
                    BasketID = customer.BasketID,
                    StockID = itemID,
                    Quantity = 1
                };
                _db.BasketItems.Add(newItem);
                await _db.SaveChangesAsync();
            }
            else
            {
                item.Quantity = item.Quantity + 1;
                _db.Attach(item).State = EntityState.Modified;
                //attempt to save changes
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex) {
                    throw new Exception($"Basket not found!", ex);
                }
            }
            return RedirectToPage();

        }


        public async Task OnGetAsync()
        {
            //retrieve all items from menuItems
            if (_db.MenuItemss != null)
            {
                MenuItems = await _db.MenuItemss.ToListAsync();
            }
        }
    }
}

CO5227_Assignment/Pages/About.cshtml
@page
@model CO5227_Assignment.Pages.AboutModel
@{
}
<div class="text-center">
    <h1 class="display-5">About Us</h1>
</div>

CO5227_Assignment/Pages/Checkout.cshtml
@page
@model CO5227_Assignment.Pages.CheckoutModel
@{
    ViewData["Title"] = "Checkout";
}
@using CO5227_Assignment.Data
@using Microsoft.Extensions.Options


<div class="text-center p-5">
    <h1 class="display-5">Checkout</h1>

    @if (Model.Items.Count <1)
    {
        <p>Your basket is empty! Select items on the menu.</p>
    }
    else
    {
        <form method="post">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        var subtotal = item.price * item.quantity;

                        <tr>
                            <td>@item.itemName</td>
                            <td>@item.price.ToString("C")</td>
                            <td>@item.quantity</td>
                            <td>@subtotal.ToString("C")</td>
                        </tr>
                    }
                </tbody>
            </table>

            <h2>Order Total: @Model.Total.ToString("C")</h2>

            <button type="submit" asp-page-handler="Buy">Buy</button>
        </form>
    }
</div>

CO5227_Assignment/Pages/Contact.cshtml
@page
@model CO5227_Assignment.Pages.ContactModel
@{
    ViewData["Title"] = "Contact";
}
<head>
    <link rel="stylesheet" href="~/css/contact.css" />
</head>
<div class="text-center">
    <h1 class="display-5 mb-3 pb-3">Contact</h1>
    <div class="d-flex justify-content-around">
        <div>
            <!-- email form -->
            <form method="post">

                <div class="form-group py-2 ">
                    <p class="fw-bold">Email</p>
                    <input asp-for="Email" />
                </div>

                <div class="form-group py-2 ">
                    <p class="fw-bold">Subject</p>
                    <input asp-for="Subject" />
                </div>

                <div class="form-group">
                    <p class="fw-bold">Message</p>
                    <label asp-for="Body" />
                    <textarea rows="5" cols="40"></textarea>
                </div>

                <button class="py-2 px-3 my-3 fw-bold" type="submit" asp-page-handler="Submit">Submit</button>

            </form>
            <div class="mb-4">
                @{

                    if (Model.isSuccessful == true)
                    {
                                <em class="text-success">Your email was sent successfully!</em>
                    }
                    else if (Model.isSuccessful == false)
                    {
                        <em class="text-danger">Your email was not sent, please try again.</em>
                    }
                }
            </div>
        </div>
        <!-- Google maps API -->
        <div id="map" class="mb-5">
           
        @try
        {
                <!-- start of adapted code from Google, 2024 -->
                <script>
                    var map;
                    function initMap() {
                    map = new google.maps.Map(document.getElementById('map'), {
                    center: { lat: 35.67401172282793, lng: 139.7715725798791 },
                    zoom: 13
                    });
                    }
                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBgkTc3kdkWWbYuYe7p4OaLYZRQFIdFPU&callback=initMap"
                async defer></script>
                <!-- end of adapted code -->
        }
        finally
        {
                <img class="d-block w-100 border border-dark border-5" src="@Url.Content("~/img/mapImg.jpg")" alt="Static image of map, enable javascript to use">
        }
        </div>
    </div>
    
    
</div>

CO5227_Assignment/Pages/adminPortal.cshtml
@page
@model CO5227_Assignment.Pages.adminPortalModel
@{
}

<div class="text-center">
    <h1 class="display-5 pb-4">Admin Portal</h1>
    <a asp-page="/AdminMenu/Index"><button class="btn btn-dark btn-lg px-5 py-3 mt-3">Admin View of Menu</button></a>
    <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2F2228246.win.studentwebserver.co.uk%2FCO5227"><button class="btn btn-dark btn-lg px-5 py-3 mt-3">Validate HTML</button></a>
    <a href="https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2F2228246.win.studentwebserver.co.uk%2FCO5227+&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en"><button class="btn btn-dark btn-lg px-5 py-3 mt-3">Validate CSS</button></a>
</div>

CO5227_Assignment/Pages/userMenuIndex.cshtml
@page
@model CO5227_Assignment.Pages.AdminMenu.userMenuModel
@{
}

@using Microsoft.AspNetCore.Identity
@using CO5227_Assignment.Models
@using CO5227_Assignment.Data;
@inject UserManager<IdentityUser> UserManager
@inject CO5227_AssignmentContext Context
<head>
    <link rel="stylesheet" href="~/css/userMenu.css" />
</head>
<body>


    <div class="text-center p-5">
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-center">
            <div class="px-5 mx-5"></div>

            <div class="mb-3 mb-md-0">
                <h1 class="display-5">Menu</h1>

                @{
                    //The below code will only display text to tell the user to log in if the user has no value
                    //(admin isnt in this table)
                    var user = await UserManager.GetUserAsync(User);
                    if (user == null)
                    {
                        <h3 class="text-danger mt-3">Log in to purchase items!</h3>
                    }
                }
            </div>

            
            <div>
                <form method="post" class="d-flex flex-column flex-md-row align-items-center">
                    <div class="mb-3 mb-md-0 me-md-3"><input asp-for="Search" />
                        <button type="submit" asp-page-handler="Search">Search</button>
                    </div>
                </form>
            </div>
        </div>


        

    </div>
    <!-- Organises items from menu into resizeable layout -->
    <div class="container">
        @for (int i = 0; i < Model.MenuItems.Count; i += 2)
        {
                <div class="row mb-4">
                @for (int j = i; j < i + 2 && j < Model.MenuItems.Count; j++)
                {
                    var item = Model.MenuItems[j];
                    <!-- displays an image for an item if it exists otherwise show the default image -->
                    <div class="col-md-6 text-center">
                        <a asp-page="/AdminMenu/Details" asp-route-id="@item.itemID">
                            @{
                                try
                                {
                                    
                                        <img id="hovering" class="img-fluid py-4" src="@string.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(item.imgData))" alt="@item.imgDescription" />
                                        
                                }
                                catch
                                {

                                        <img id="hovering" class="img-fluid" src="~/img/noimg.png" alt="No image found" />
                                    
                                }
                            }
                        </a>
                        <div>
                            <ul class="list-unstyled">
                                    <li><h5>@Html.DisplayFor(modelItem => item.itemName)</h5></li>
                                    @{
                                        //The below code will only display the add to basket button if the user exists and is in the CheckoutCustomers table
                                        //(admin isnt in this table)
                                        
                                        if (user != null)
                                        {
                                            CheckoutCustomer customer = await Context.CheckoutCustomers.FindAsync(user.Email);
                                            if (customer != null)
                                            {
                                                <form method="post">
                                            <li><button class="btn btn-dark btn-outline-light px-3 py-1" type="submit" asp-page-handler="Buy" asp-route-itemID="@item.itemID">Add to basket</button></li>
                                                </form>
                                            }
                                            
                                        }
                                    
                                    }
                                    
                                    
                            </ul>
                                
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>
</body>